--표준 SQL 99 이용해서, 조인의 표현식 연습

--기본 문법 예시
--NATURAL JOIN

SELECT * FROM EMP NATURAL JOIN DEPT; 

--JOING USING

SELECT ENAME, DNAME
FROM EMP JOIN DEPT USING(DEPTNO);    --EMP 테이블과 DEPT 테이블을 합치는데 DEPTNO을 USING해서 기준으로 같은 것만


--JOIN ON 가장 많이 사용하는 포맷 형식
SELECT ENAME, DNAME
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;   


-- LEFT OUTER JOIN, 왼쪽 외부 조인
SELECT ENAME, DNAME
FROM EMP LEFT OUTER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;   --OUTER 생략 가능

--RIGHT
SELECT ENAME, DNAME
FROM EMP RIGHT OUTER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;   --OUTER 생략 가능

SELECT ENAME, DNAME
FROM EMP FULL OUTER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;   --OUTER 생략 가능



--3개 이상 테이블 조인
SELECT EMP.ENAME, DEPT.DNAME, LOCATION.LOC_ID
FROM EMP 
JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO        --EMP 와 DEPT를 붙인다. 뭘 기준으로? ON 뒤에 있는 EMP.DEPTNO, DEPT.DEPTNO를 기준으로. ON은 EMP와 DEPT에 적용됨.
JOIN LOCATION ON DEPT.DEPTNO = LOCATION.LOC_ID;

SELECT * FROM DEPT;
SELECT * FROM LOCATION;

--임시 생성 테이블 LOCATION이라는 이름을 만든 뒤 임의로 데이터를 넣으려고
CREATE TABLE LOCATION (
LOC_ID NUMBER PRIMARY KEY,
LOC VARCHAR2(50)
);





--퀴즈 1 JOIN...on을 사용하여 EMP와 DEPT를 등가 조인하시오.

SELECT ENAME, DNAME
FROM EMP JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;   


--퀴즈 2. NATURAL JOIN으로 EMP와 DEPT를 연결하시오

SELECT * FROM EMP NATURAL JOIN DEPT; 

--퀴즈3. USING 을 사용해 조인하되, 부서명이 있는 사원만 출력하시오.
SELECT ENAME, DNAME
FROM EMP JOIN DEPT USING(DEPTNO);   

--퀴즈4. LEFT OUTER JOIN을 사용해 부서가 없는 사원도 포함한 결과를 출력하시오
SELECT ENAME, DNAME
FROM EMP LEFT OUTER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;  

--퀴즈 5. EMP, DEPT, LOCATION  테이블을 SQL-99방식으로 연결하여 
--사원이름, 부서명, 지역명을 출력하시오.
SELECT EMP.ENAME AS "사원이름", DEPT.DNAME AS "부서이름", LOCATION.LOC_ID AS "지역이름"
FROM EMP 
JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO        --EMP 와 DEPT를 붙인다. 뭘 기준으로? ON 뒤에 있는 EMP.DEPTNO, DEPT.DEPTNO를 기준으로. ON은 EMP와 DEPT에 적용됨.
JOIN LOCATION ON DEPT.DEPTNO = LOCATION.LOC_ID;


--시도. ON에는 =가 3개 이상 적용 안 됨. 그래서 지움.
SELECT EMP.ENAME, DEPT.DNAME, LOCATION.LOC_ID
FROM EMP 
JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
JOIN LOCATION ON EMP.DEPTNO = LOCATION.LOC_ID;   



--퀴즈 6. FULL OUTER JOIN으로 사원이 없는 부서와 부서가 없는 사원을 모두 출력하시오.


SELECT ENAME, DNAME
FROM EMP FULL OUTER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO; 
